components {
  id: "explode"
  component: "/assets/vfx/orangeExplode.particlefx"
}
components {
  id: "obstacle"
  component: "/main/game/enemycoins/enemies/obstacle/obstacle.script"
}
embedded_components {
  id: "sprite"
  type: "sprite"
  data: "default_animation: \"obstacle_2\"\n"
  "material: \"/builtins/materials/sprite.material\"\n"
  "textures {\n"
  "  sampler: \"texture_sampler\"\n"
  "  texture: \"/main/game/sprites.atlas\"\n"
  "}\n"
  ""
  position {
    z: 0.1
  }
}
embedded_components {
  id: "collisionobject"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_KINEMATIC\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"enemy\"\n"
  "mask: \"player\"\n"
  "mask: \"shield\"\n"
  "mask: \"rocket\"\n"
  "mask: \"radar\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      x: 13.0\n"
  "      y: -19.0\n"
  "    }\n"
  "    rotation {\n"
  "      z: 0.16984983\n"
  "      w: 0.98546994\n"
  "    }\n"
  "    index: 0\n"
  "    count: 3\n"
  "  }\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      x: -14.0\n"
  "      y: 14.0\n"
  "    }\n"
  "    rotation {\n"
  "      z: 0.16984983\n"
  "      w: 0.98546994\n"
  "    }\n"
  "    index: 3\n"
  "    count: 3\n"
  "  }\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      x: 16.0\n"
  "    }\n"
  "    rotation {\n"
  "      z: 0.25798175\n"
  "      w: 0.9661498\n"
  "    }\n"
  "    index: 6\n"
  "    count: 3\n"
  "  }\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      x: 11.0\n"
  "      y: -1.0\n"
  "    }\n"
  "    rotation {\n"
  "      z: -0.26830578\n"
  "      w: 0.9633338\n"
  "    }\n"
  "    index: 9\n"
  "    count: 3\n"
  "  }\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      x: -10.0\n"
  "      y: 32.0\n"
  "    }\n"
  "    rotation {\n"
  "      z: 0.25798175\n"
  "      w: 0.9661498\n"
  "    }\n"
  "    index: 12\n"
  "    count: 3\n"
  "  }\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      x: -16.0\n"
  "      y: 32.0\n"
  "    }\n"
  "    rotation {\n"
  "      z: -0.26830578\n"
  "      w: 0.9633338\n"
  "    }\n"
  "    index: 15\n"
  "    count: 3\n"
  "  }\n"
  "  data: 19.05509\n"
  "  data: 16.475365\n"
  "  data: 10.0\n"
  "  data: 19.558735\n"
  "  data: 16.475365\n"
  "  data: 10.0\n"
  "  data: 3.8451376\n"
  "  data: 10.0\n"
  "  data: 10.0\n"
  "  data: 3.8451376\n"
  "  data: 10.0\n"
  "  data: 10.0\n"
  "  data: 3.8451376\n"
  "  data: 10.0\n"
  "  data: 10.0\n"
  "  data: 3.8451376\n"
  "  data: 10.0\n"
  "  data: 10.0\n"
  "}\n"
  ""
}
