components {
  id: "alien_car"
  component: "/main/game/enemycoins/enemies/alien_car/alien_car.script"
}
components {
  id: "greenExplode"
  component: "/assets/vfx/greenExplode.particlefx"
}
embedded_components {
  id: "sprite"
  type: "sprite"
  data: "default_animation: \"alien\"\n"
  "material: \"/builtins/materials/sprite.material\"\n"
  "textures {\n"
  "  sampler: \"texture_sampler\"\n"
  "  texture: \"/main/game/sprites.atlas\"\n"
  "}\n"
  ""
  scale {
    x: 0.4
    y: 0.3
  }
}
embedded_components {
  id: "collisionobject"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_KINEMATIC\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"enemy\"\n"
  "mask: \"player\"\n"
  "mask: \"shield\"\n"
  "mask: \"rocket\"\n"
  "mask: \"radar\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      x: 21.0\n"
  "      y: -31.0\n"
  "    }\n"
  "    rotation {\n"
  "      z: 0.21905066\n"
  "      w: 0.9757135\n"
  "    }\n"
  "    index: 0\n"
  "    count: 3\n"
  "    id: \"tentacleInnerLeft\"\n"
  "  }\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      x: -22.0\n"
  "      y: -31.0\n"
  "    }\n"
  "    rotation {\n"
  "      z: -0.22274172\n"
  "      w: 0.9748775\n"
  "    }\n"
  "    index: 3\n"
  "    count: 3\n"
  "    id: \"tentacleInnerRight\"\n"
  "  }\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      x: -17.0\n"
  "      y: -39.0\n"
  "    }\n"
  "    rotation {\n"
  "      z: 0.46922675\n"
  "      w: 0.88307774\n"
  "    }\n"
  "    index: 6\n"
  "    count: 3\n"
  "    id: \"tentacleOuterRight\"\n"
  "  }\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      x: 16.0\n"
  "      y: -40.0\n"
  "    }\n"
  "    rotation {\n"
  "      z: -0.47162595\n"
  "      w: 0.88179874\n"
  "    }\n"
  "    index: 9\n"
  "    count: 3\n"
  "    id: \"tentacleOuterLeft\"\n"
  "  }\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      y: -4.0\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 12\n"
  "    count: 3\n"
  "    id: \"body\"\n"
  "  }\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      y: -17.0\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 15\n"
  "    count: 3\n"
  "    id: \"wing\"\n"
  "  }\n"
  "  data: 2.911572\n"
  "  data: 7.070112\n"
  "  data: 10.0\n"
  "  data: 2.7368774\n"
  "  data: 6.986989\n"
  "  data: 9.4\n"
  "  data: 1.686\n"
  "  data: 7.2626185\n"
  "  data: 9.4\n"
  "  data: 1.686\n"
  "  data: 6.631595\n"
  "  data: 9.4\n"
  "  data: 15.056635\n"
  "  data: 33.123627\n"
  "  data: 10.0\n"
  "  data: 31.842094\n"
  "  data: 6.3901453\n"
  "  data: 10.0\n"
  "}\n"
  ""
}
