components {
  id: "alien_red"
  component: "/main/game/enemycoins/enemies/alien_red/alien_red.script"
}
components {
  id: "redExplode"
  component: "/assets/vfx/redExplode.particlefx"
}
embedded_components {
  id: "sprite"
  type: "sprite"
  data: "default_animation: \"alien_red\"\n"
  "material: \"/builtins/materials/sprite.material\"\n"
  "textures {\n"
  "  sampler: \"texture_sampler\"\n"
  "  texture: \"/main/game/sprites.atlas\"\n"
  "}\n"
  ""
  scale {
    x: 0.4
    y: 0.4
  }
}
embedded_components {
  id: "collisionobject"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_KINEMATIC\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"enemy\"\n"
  "mask: \"player\"\n"
  "mask: \"shield\"\n"
  "mask: \"rocket\"\n"
  "mask: \"radar\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_SPHERE\n"
  "    position {\n"
  "      y: -12.0\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 0\n"
  "    count: 1\n"
  "    id: \"body\"\n"
  "  }\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      x: -21.0\n"
  "      y: -43.0\n"
  "    }\n"
  "    rotation {\n"
  "      z: 0.32556817\n"
  "      w: 0.94551855\n"
  "    }\n"
  "    index: 1\n"
  "    count: 3\n"
  "    id: \"tentacleOuterRight\"\n"
  "  }\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      x: 21.0\n"
  "      y: -43.0\n"
  "    }\n"
  "    rotation {\n"
  "      z: -0.32643282\n"
  "      w: 0.9452204\n"
  "    }\n"
  "    index: 4\n"
  "    count: 3\n"
  "    id: \"tentacleOuterLeft\"\n"
  "  }\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      x: -7.0\n"
  "      y: -48.0\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 7\n"
  "    count: 3\n"
  "    id: \"tentacleInnerRight\"\n"
  "  }\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      x: 7.0\n"
  "      y: -48.0\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 10\n"
  "    count: 3\n"
  "    id: \"tentacleInnerLeft\"\n"
  "  }\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      x: 8.0\n"
  "      y: 30.0\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 13\n"
  "    count: 3\n"
  "    id: \"legTopLeft\"\n"
  "  }\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      x: -9.0\n"
  "      y: 21.0\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 16\n"
  "    count: 3\n"
  "    id: \"legRight\"\n"
  "  }\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      x: 9.0\n"
  "      y: 21.0\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 19\n"
  "    count: 3\n"
  "    id: \"legLeft\"\n"
  "  }\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      x: -7.0\n"
  "      y: 30.0\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 22\n"
  "    count: 3\n"
  "    id: \"legTopRight\"\n"
  "  }\n"
  "  data: 30.934107\n"
  "  data: 2.1149986\n"
  "  data: 10.0\n"
  "  data: 10.0\n"
  "  data: 2.1149986\n"
  "  data: 10.0\n"
  "  data: 10.0\n"
  "  data: 1.1384665\n"
  "  data: 5.4108005\n"
  "  data: 10.0\n"
  "  data: 1.1384665\n"
  "  data: 5.4108005\n"
  "  data: 10.0\n"
  "  data: 1.2978705\n"
  "  data: 3.4308655\n"
  "  data: 10.0\n"
  "  data: 2.980277\n"
  "  data: 5.24762\n"
  "  data: 10.0\n"
  "  data: 2.980277\n"
  "  data: 5.24762\n"
  "  data: 10.0\n"
  "  data: 1.441379\n"
  "  data: 3.4308655\n"
  "  data: 10.0\n"
  "}\n"
  ""
}
embedded_components {
  id: "laserFactory"
  type: "factory"
  data: "prototype: \"/main/game/enemycoins/enemies/alien_red/laser.go\"\n"
  ""
}
